var res = {
    title_logo_png : "res/title_logo.png",
    start_logo_png : "res/start_logo.png",
    background_sky_png: "res/background_sky.png",
    background_sea_png: "res/background_sea.png",
    background_space_png: "res/background_space.png",
    player_sky01_png : "res/player01.png",
    player_sky02_png : "res/player02.png",
    player_sky03_png : "res/player03.png",
    player_sea01_png : "res/player01.png",
    player_sea02_png : "res/player02.png",
    player_sea03_png : "res/player03.png",
    player_space01_png : "res/player01.png",
    player_space02_png : "res/player02.png",
    player_space03_png : "res/player03.png",
    item_plus00_png : "res/item_plus00.png",
    item_plus01_png : "res/item_plus01.png",
    item_minus00_png : "res/item_minus00.png",
    item_minus01_png : "res/item_minus01.png",
    sponser_board_png : "res/sponser_board.png",
    sponser_logo_png : "res/sponser_logo.png",
    goal_flag_png : "res/goal_flag.png",
    goal_chara_png : "res/goal_chara.png",
    gameover_logo_png : "res/gameover_logo.png",
    ground_sky_png : "res/ground_sky.png",
    ground_sea_png : "res/ground_sea.png",
    ground_space_png : "res/ground_space.png",
    retry_logo_png : "res/retry_logo.png",
    stageclear_logo_png : "res/stageclear_logo.png",
    nextstage_logo_png : "res/nextstage_logo.png",
    button_png : "res/button.png",
    buttonback_png: "res/button_back.png",
    title_bgm_mp3: "res/title_bgm.mp3",
    stagesky_bgm_mp3: "res/title_bgm.mp3",
    stagesea_bgm_mp3: "res/title_bgm.mp3",
    stagespace_bgm_mp3: "res/title_bgm.mp3",
    stageclear_bgm_mp3: "res/title_bgm.mp3",
    plus_se_mp3 : "res/plus_se.mp3",
    damage_se_mp3 : "res/damage_se.mp3",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}